# Generated by Django 4.1 on 2022-08-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.CharField(db_index=True, default="What's Happening?", max_length=140, verbose_name='Body'),
        ),
    ]
